added a native test for game stages
vinsburg/sorting-game pull request #2
Opened 2024-10-05 09:51 UTC by solebox

added a native test for game stages

2024-10-05 09:52 UTC, solebox commented
@vinsburg pull request incoming first naive test ;)

2024-10-05 11:45 UTC, vinsburg requested changes
Awsome test, thanks for contributing!

2024-10-05 11:45 UTC, vinsburg commented on Cargo.toml
> +log = "0.4.22"
Logger seems, unsued, please remove it.
I'm keeping the project dependency free for now.

2024-10-05 11:45 UTC, vinsburg commented on src/game/mod.rs
> +    use log::debug;
Should be removed aswell.

2024-10-05 11:45 UTC, vinsburg commented on src/game/stack/mod.rs
> +
I've fixed spacing at a later commit, please delete  as well :pray:

2024-10-11 14:57 UTC, merged

2024-10-18 11:25 UTC, solebox commented
oh dang i missed the comments, this pr gave me another idea